"""Initial migration

Revision ID: 66716a33a005
Revises:
Create Date: 2025-06-15 23:37:33.012416+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = "66716a33a005"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
